### ISSUE TITLE
Stack Trace: Error in _removeEmptyTags function

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1650]
We are using slickgrid and there is a known conflict with slickgrid's drag event library and your drag event names.   I think it's causing the following stack trace in that some drag event from slick grid is triggering a paste function in froala, but because it's coming from slickgrid drag event it's passing different args that you would be expecting. Therefore, there was a condition that you did not expect to check. You should validate the input args because other libraries using the same drag event names may cause this issue as well.

```
Error Message:
Uncaught Exception in event handler.
Event Type: paste
Event Namespace: undefined
Target Element: DIV
ID: undefined
Classes: fr-element fr-view
Event Target Element: BR
ID: undefined
Classes: undefined
Exception Message: Failed to execute 'querySelector' on 'Element': '*:last' is not a valid selector.
Exception Name: SyntaxError
Exception Stack Trace: Error: Failed to execute 'querySelector' on 'Element': '*:last' is not a valid selector.
at _removeEmptyTags (https://veoci.com/static/cc-3baac7fd/uncompressed/froala/js/froala_editor.js:9598:23)
at _processPaste (https://veoci.com/static/cc-3baac7fd/uncompressed/froala/js/froala_editor.js:9465:26)
at FE._handlePaste (https://veoci.com/static/cc-3baac7fd/uncompressed/froala/js/froala_editor.js:9197:11)
at trigger (https://veoci.com/static/cc-3baac7fd/uncompressed/froala/js/froala_editor.js:1056:32)
at HTMLDivElement.<anonymous> (https://veoci.com/static/cc-3baac7fd/uncompressed/froala/js/froala_editor.js:726:9)
at HTMLDivElement.dispatch (https://veoci.com/static/cc-3baac7fd/uncompressed/bower_components/jquery/dist/jquery.js:4435:9)
at HTMLDivElement.jQuery.event.dispatch (https://veoci.com/static/cc-3baac7fd/uncompressed/js/soschat-common.js:357:36)
at HTMLDivElement.$event.dispatch (https://veoci.com/static/cc-3baac7fd/uncompressed/bower_components/slickgrid-bower-custom/lib/jquery.event.drag-2.2.js:374:19)
at HTMLDivElement.elemData.handle (https://veoci.com/static/cc-3baac7fd/uncompressed/bower_components/jquery/dist/jquery.js:4121:28)
```

**Comment by jpgilchrist** [comment]
FYI I think we handled this by scoping our slickgrid drag event library more strictly...
