### ISSUE TITLE
angular-froala - Cannot go to other state <$state.go(newState)> 

### ISSUE THREAD

**Issue by trungntq** [froala/wysiwyg-editor#3091]
On state which contain wysiwyg-editor, I have a button which lead my app to other page (state).
`$state.go(Constants.states.searchPage);`
But I meet this error:

> DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at HTMLDivElement.<anonymous> (http://localhost:8000/bower_components/jquery/jquery.js:5523:12)
    at init.domManip (http://localhost:8000/bower_components/jquery/jquery.js:5588:15)
    at init.replaceWith (http://localhost:8000/bower_components/jquery/jquery.js:5517:8)
    at Object.destroy (http://localhost:8000/bower_components/froala-wysiwyg-editor/js/froala_editor.min.js:7:80782)
    at s.destroy (http://localhost:8000/bower_components/froala-wysiwyg-editor/js/froala_editor.min.js:7:5405)
    at HTMLTextAreaElement.<anonymous> (http://localhost:8000/bower_components/froala-wysiwyg-editor/js/froala_editor.min.js:7:5880)
    at Function.each (http://localhost:8000/bower_components/jquery/jquery.js:590:23)
    at init.each (http://localhost:8000/bower_components/jquery/jquery.js:237:17)
    at init.M.fn.froalaEditor (http://localhost:8000/bower_components/froala-wysiwyg-editor/js/froala_editor.min.js:7:5606)
    at Scope.$scope.goToSearch (http://localhost:8000/app/controllers/client/client.create.controller.js:32:29)

Can anyone give me some advice on this, please.
Many thanks

**Comment by stefanneculai** [comment]
@trungntq for any questions regarding the Angular plugin, please open the issue directly there.
