### ISSUE TITLE
Uncaught exception when removing a table row via Row > Delete row

### ISSUE THREAD

**Issue by earshinov** [froala/wysiwyg-editor#4086]
### Repro steps

1. Open any page with a Froala editor, e.g. https://froala.com/wysiwyg-editor/examples/resize-table/
2. Using code view, insert the following HTML into the editor:

```html
<table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse;" width="400">
	<tbody>
		<tr>
			<td class="xl78" rowspan="6">
				<br>
			</td>
			<td class="xl81" colspan="2">
				<br>
			</td>
			<td class="xl65">here</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
		</tr>
		<tr>
			<td class="xl75" rowspan="2">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
		</tr>
		<tr>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
			<td class="xl65">
				<br>
			</td>
		</tr>
	</tbody>
</table>
```

3. Select the "here" cell
4. In the panel that appeared, select Row > Delete row

![froala delete row](https://user-images.githubusercontent.com/52021/98279062-8323e080-1faa-11eb-8062-7d999ffc1b13.png)

Expected result:
- The row is deleted

Actual result:
- The row is deleted…
- …but there is an error message in DevTools console

Exception message (Froala 3.2.3):

```
table.js?version=1.0.1:1190 Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at _updateRowspan (table.js?version=1.0.1:1190)
    at _updateCellSpan (table.js?version=1.0.1:1255)
    at Object.deleteRow (table.js?version=1.0.1:801)
    at C.Bootstrap.callback (table.js?version=1.0.1:3486)
    at Object.n [as exec] (froala_editor.pkgd.min.js?version=1.0.1:7)
    at o (froala_editor.pkgd.min.js?version=1.0.1:7)
    at r (froala_editor.pkgd.min.js?version=1.0.1:7)
    at t (froala_editor.pkgd.min.js?version=1.0.1:7)
    at C.Bootstrap.c (froala_editor.pkgd.min.js?version=1.0.1:7)
    at a (froala_editor.pkgd.min.js?version=1.0.1:7)
```

Exception message (Froala 3.2.2 locally with minified sources):

```
TypeError: Cannot read property '1' of undefined
--
at v (webpack:/./node_modules/froala-editor/js/plugins.pkgd.min.js:7:445691)
at E (webpack:/./node_modules/froala-editor/js/plugins.pkgd.min.js:7:446057)
at deleteRow (webpack:/./node_modules/froala-editor/js/plugins.pkgd.min.js:7:470250)
at apply (webpack:/./node_modules/froala-editor/js/plugins.pkgd.min.js:7:478675)
at exec (webpack:/./node_modules/froala-editor/js/froala_editor.min.js:7:37639)
...
(13 additional frame(s) were not displayed)
```

In the second case, the error happens on the line marked with `>>>`:

```js
function v(e, t, a) {
  var n,
    i,
    r,
    o,
    s,
    l = 0,
    c = S(a);
  if (e < (t = Math.min(t, c.length - 1)))
    for (n = e; n <= t; n++)
      if (!(e < n && c[n][0] == c[n - 1][0]) && 1 < (o = Math.min(parseInt(c[n][0].getAttribute("rowspan"), 10) || 1, t - e + 1)) && c[n][0] == c[n + 1][0])
        for (l = o - 1, i = 1; i < c[0].length; i++)
          if (c[n][i] != c[n][i - 1]) {
            for (r = n; r < n + o; r++)
              /* >>> */ if (1 < (s = parseInt(c[r][i].getAttribute("rowspan"), 10) || 1) && c[r][i] == c[r + 1][i]) r += l = Math.min(l, s - 1);
              else if (!(l = Math.max(0, l - 1))) break;
            if (!l) break;
          }
  l && b(c, l, "rowspan", e, t, 0, c[0].length - 1);
}
```

### Version information

Froala: Reproducible in versions 3.2.2 and 3.2.3 at least
Browser: Chrome Google Chrome 86.0.4240.75 (Official Build) (32-bit)

**Comment by earshinov** [comment]
No longer reproducible in 4.0.9
