### ISSUE TITLE
Initialization throws an error if the container element is removed

### ISSUE THREAD

**Issue by dcsaszar** [froala/wysiwyg-editor#4407]
We're observing this behavior in the context of a dynamic (React) app.
Sometimes these appear to happen in rapid succession:

1. The container element is created
2. Froala is initialized for the element
3. The element is removed

##### Expected behavior.

No error is thrown by the Froala initialization.

##### Actual behavior.

Depending on the config:

`{ height: 150, iframe: true }`:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getComputedStyle')
```
`{ iframe: true }`:
```
Uncaught TypeError: Cannot read properties of null (reading 'FormData')
```

##### Steps to reproduce the problem.

https://jsfiddle.net/g5fpq83k/

##### Editor version.

4.0.9

##### OS.

macOs 11.6.2

##### Browser.

Chrome 98.0.4758.80

##### Recording.

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/986170/153920355-4b652db2-497f-47f9-9073-ead343e4b020.png">

**Comment by mateuszkoz** [comment]
Any update/solution on this issue? Have same problem.

**Comment by elninoisback** [comment]
I'm having the same issue on an Angular app. Anyone solved this?

**Comment by MichaelSemchenko** [comment]
as I see in [4.6 changelog](https://froala.com/wysiwyg-editor/changelog/), 
```
Fixed, `Error: Cannot read properties of undefined (reading 'disableBlur')` in React Editor with `fullPage` or `iframe` Mode
```

That error is gone for me, but another one has appeared:
```
froala_editor.min.js:7240 Uncaught TypeError: Cannot read properties of undefined (reading 'getComputedStyle')
    at E.css (froala_editor.min.js:7240:62)
    at o (froala_editor.min.js:5167:400)
    at Object.t [as _init] (froala_editor.min.js:5172:17)
    at L.Bootstrap.load (froala_editor.min.js:7689:69)
    at L.Bootstrap.x (froala_editor.min.js:181:79)
```

**Comment by MichaelSemchenko** [comment]
as I see in [4.6 changelog](https://froala.com/wysiwyg-editor/changelog/), 
```
Fixed, `Error: Cannot read properties of undefined (reading 'disableBlur')` in React Editor with `fullPage` or `iframe` Mode
```

That error is gone for me, but another one mentioned by author has appeared:
```
froala_editor.min.js:7240 Uncaught TypeError: Cannot read properties of undefined (reading 'getComputedStyle')
    at E.css (froala_editor.min.js:7240:62)
    at o (froala_editor.min.js:5167:400)
    at Object.t [as _init] (froala_editor.min.js:5172:17)
    at L.Bootstrap.load (froala_editor.min.js:7689:69)
    at L.Bootstrap.x (froala_editor.min.js:181:79)
```

**Comment by SimonTweddle1** [comment]
4 years open :'(
