### ISSUE TITLE
Add iframe opts (Cannot read properties of null (reading 'FormData'))

### ISSUE THREAD

**Issue by Devolick** [froala/wysiwyg-editor#4558]
##### Expected behavior.
Wrap content with iFrame

##### Actual behavior.
ERROR TypeError: Cannot read properties of null (reading 'FormData')
    at e (node_modules\froala-editor\js\froala_editor.pkgd.min.js:7:177307)
    at Object.a [as _init] (node_modules\froala-editor\js\froala_editor.pkgd.min.js:7:177422)
    at C.Bootstrap.load (node_modules\froala-editor\js\froala_editor.pkgd.min.js:7:456331)
    at C.Bootstrap.E (node_modules\froala-editor\js\froala_editor.pkgd.min.js:7:452581)
    at timer (zone.js:2405:41)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26261:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at invokeTask (zone.js:487:34)

##### Steps to reproduce the problem.
Just add in opts iframe: true and bind [froalaEditor]="opts" or new FroalaEditor('<id>', opts)

##### Editor version.
"angular-froala-wysiwyg": "^4.0.16"
 "@angular/core": "^14.2.12",

##### OS.
Windows 11

##### Browser.
Microsoft Edge
Version 107.0.1418.62 (Official build) (64-bit)
Google Chrome
Version 107.0.5304.122 (Official build), (64-bit)

**Comment by Devolick** [comment]
With version 4.0.17 working.
