### ISSUE TITLE
Error if a link is deleted in a table

### ISSUE THREAD

**Issue by cguglielmo** [froala/wysiwyg-editor#4619]
##### Expected behavior.
Deleting a link in a table does not throw an error.

##### Actual behavior.
Deleting a link in a table throws an error.

##### Steps to reproduce the problem.
1. Open https://jsfiddle.net/q8pce7a3/1/
2. Open Browser Console
3. Select the link (aaa).
4. Press delete -> The browser console shows the following error

froala_editor.pkgd.min.js:7 Uncaught TypeError: Cannot read properties of null (reading 'parentElement')
    at m (froala_editor.pkgd.min.js:7:143297)
    at C.Bootstrap.s (froala_editor.pkgd.min.js:7:146428)
    at v (froala_editor.pkgd.min.js:7:31614)
    at HTMLDivElement.<anonymous> (froala_editor.pkgd.min.js:7:33002)
    at HTMLDivElement.<anonymous> (froala_editor.pkgd.min.js:7:435072)
m

##### Editor version.
Tested with 4.0.18 and 4.0.17. Fails with both versions.

##### OS.
Windows 10

##### Browser.
Chrome

##### Recording.
https://user-images.githubusercontent.com/2082602/233955334-c5f1ab18-17dc-4328-90be-f7ecd27c50e6.MP4

**Comment by cguglielmo** [comment]
It seems to be solved with 4.7.1.

https://jsfiddle.net/f0kn3qvm/
